package types

const ()

type EventType string

const (
	EVENT_TYPE_MESSAGE           EventType = "GAME_MESSAGE"
	EVENT_TYPE_MESSAGE_REJECTED  EventType = "GAME_MESSAGE_REJECTED"
	EVENT_TYPE_LIKE_MESSAGE      EventType = "GAME_LIKE_MESSAGE"
	EVENT_TYPE_DISLIKE_MESSAGE   EventType = "GAME_DISLIKE_MESSAGE"
	EVENT_TYPE_LIKE_QUESTION     EventType = "GAME_LIKE_QUESTION"
	EVENT_TYPE_ANSWER_QUESTION   EventType = "GAME_ANSWER_QUESTION"
	EVENT_TYPE_POLL_VOTE         EventType = "GAME_POLL_VOTE"
	EVENT_TYPE_CORRECT_POLL_VOTE EventType = "GAME_CORRECT_POLL_VOTE"
	EVENT_TYPE_ATTENTION         EventType = "ATTENTION_CONTROL_DONE"
)
